-- Library Management Migration Script


CREATE TABLE IF NOT EXISTS public.author
(
    document_id bigint NOT NULL,
    person_id bigint NOT NULL,
    CONSTRAINT author_pkey PRIMARY KEY (document_id, person_id),
    CONSTRAINT fk6hvf724whhl6gil5s4l1jefje FOREIGN KEY (document_id)
        REFERENCES public.document (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fkd8cm5fy8qunfotg4xpdi1wad7 FOREIGN KEY (person_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)


CREATE TABLE IF NOT EXISTS public.book
(
    category character varying(255) COLLATE pg_catalog."default",
    edition integer NOT NULL,
    isbn character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    year integer NOT NULL,
    document_id bigint NOT NULL,
    published_by_id bigint NOT NULL,
    CONSTRAINT book_pkey PRIMARY KEY (document_id),
    CONSTRAINT fk3idh6pescpo2ay9h00k3v44p6 FOREIGN KEY (published_by_id)
        REFERENCES public.publisher (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk62e1mk4is3ldor7vqv6q9e2h6 FOREIGN KEY (document_id)
        REFERENCES public.document (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)


CREATE TABLE IF NOT EXISTS borrow_return
(
    borrow_date timestamp without time zone NOT NULL,
    due_date timestamp without time zone,
    is_overdue boolean NOT NULL,
    return_date timestamp without time zone,
    copy_id bigint NOT NULL,
    borrowed_by_id bigint NOT NULL,
    CONSTRAINT borrow_return_pkey PRIMARY KEY (borrow_date, borrowed_by_id, copy_id),
    CONSTRAINT borrowreturn_member_borrowed_by_id_fkey FOREIGN KEY (borrowed_by_id)
        REFERENCES member (id),
    CONSTRAINT borrowreturn_copy_copy_id_fkey FOREIGN KEY (copy_id)
        REFERENCES copy (id)
);


CREATE TABLE IF NOT EXISTS cite
(
    cited_document_id bigint NOT NULL,
    cited_by_document_id bigint NOT NULL,
    CONSTRAINT cite_pkey PRIMARY KEY (cited_by_document_id, cited_document_id),
    CONSTRAINT cite_document_cited_by_document_id_fkey FOREIGN KEY (cited_by_document_id)
        REFERENCES document (id),
    CONSTRAINT cite_document_cited_document_id_fkey FOREIGN KEY (cited_document_id)
        REFERENCES document (id)
);


CREATE TABLE IF NOT EXISTS contributor
(
    person_id bigint NOT NULL,
    issue_id bigint NOT NULL,
    CONSTRAINT contributor_pkey PRIMARY KEY (issue_id, person_id),
    CONSTRAINT contributor_issue_issue_id_fkey FOREIGN KEY (issue_id)
        REFERENCES issue (id),
    CONSTRAINT contributor_person_person_id_fkey FOREIGN KEY (person_id)
        REFERENCES person (id)
);


CREATE TABLE IF NOT EXISTS public.copy
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    level integer NOT NULL,
    room_number integer NOT NULL,
    copy_of_document_id bigint NOT NULL,
    CONSTRAINT copy_pkey PRIMARY KEY (id),
    CONSTRAINT fkk9jkpblc99592dtx5wqo6t97n FOREIGN KEY (copy_of_document_id)
        REFERENCES public.document (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)


CREATE TABLE IF NOT EXISTS document
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_date timestamp without time zone,
    deleted_date timestamp without time zone,
    hierarchical_classification character varying(255),
    updated_date timestamp without time zone,
    created_by_id bigint NOT NULL,
    deleted_by_id bigint,
    updated_by_id bigint,
    CONSTRAINT document_pkey PRIMARY KEY (id),
    CONSTRAINT document_created_by_id_librarian_fkey FOREIGN KEY (created_by_id)
        REFERENCES librarian (id),
    CONSTRAINT document_deleted_by_id_librarian_fkey FOREIGN KEY (deleted_by_id)
        REFERENCES librarian (id),
    CONSTRAINT document_updated_by_id_librarian_fkey FOREIGN KEY (updated_by_id)
        REFERENCES librarian (id)
);


CREATE TABLE IF NOT EXISTS editor
(
    person_id bigint NOT NULL,
    issue_id bigint NOT NULL,
    CONSTRAINT editor_pkey PRIMARY KEY (issue_id, person_id),
    CONSTRAINT editor_person_id_person_fkey FOREIGN KEY (person_id)
    REFERENCES person (id),
    CONSTRAINT editor_issue_id_issue_fkey FOREIGN KEY (issue_id)
    REFERENCES issue (id)
);


CREATE TABLE IF NOT EXISTS issue
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    published_at timestamp without time zone,
    title character varying(255),
    published_by_id bigint,
    CONSTRAINT issue_pkey PRIMARY KEY (id),
    CONSTRAINT issue_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id)
);


CREATE TABLE IF NOT EXISTS issued_in
(
    magazine_id bigint NOT NULL,
    issue_id bigint NOT NULL,
    CONSTRAINT issued_in_pkey PRIMARY KEY (issue_id, magazine_id),
    CONSTRAINT issued_in_issue_id_issue_fkey FOREIGN KEY (issue_id)
    REFERENCES issue (id),
    CONSTRAINT issued_in_magazine_id_magazine_fkey FOREIGN KEY (magazine_id)
    REFERENCES magazine (id)
);


CREATE TABLE IF NOT EXISTS journal
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    edition integer NOT NULL,
    title character varying(255),
    published_by_id bigint NOT NULL,
    CONSTRAINT journal_pkey PRIMARY KEY (id),
    CONSTRAINT journal_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id)
);


CREATE TABLE IF NOT EXISTS journal_article
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(255),
    journal_id bigint NOT NULL,
    journal_article_document_id bigint,
    CONSTRAINT journal_article_pkey PRIMARY KEY (id),
    CONSTRAINT journal_article_journal_article_document_id_document_fkey FOREIGN KEY (journal_article_document_id)
    REFERENCES document (id),
    CONSTRAINT journal_article_journal_id_journal_fkey FOREIGN KEY (journal_id)
    REFERENCES journal (id)
);


CREATE TABLE IF NOT EXISTS keyword
(
    keyword character varying(255),
    document_id bigint NOT NULL,
    CONSTRAINT keyword_pkey PRIMARY KEY (document_id),
    CONSTRAINT keyword_document_id_document_fkey FOREIGN KEY (document_id)
    REFERENCES document (id)
);


CREATE TABLE IF NOT EXISTS public.librarian
(
    user_id bigint NOT NULL,
    CONSTRAINT librarian_pkey PRIMARY KEY (user_id),
    CONSTRAINT fkyf2jsjbxmnic68p6un7arncq FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)



CREATE TABLE IF NOT EXISTS magazine
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    edition integer NOT NULL,
    name character varying(255),
    magazine_document_id bigint,
    published_by_id bigint NOT NULL,
    CONSTRAINT magazine_pkey PRIMARY KEY (id),
    CONSTRAINT magazine_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id),
    CONSTRAINT magazine_magazine_document_id_document_fkey FOREIGN KEY (magazine_document_id)
    REFERENCES document (id)
);


CREATE TABLE IF NOT EXISTS public.member
(
    membership_coverage timestamp without time zone,
    user_id bigint NOT NULL,
    librarian_user_id bigint NOT NULL,
    CONSTRAINT member_pkey PRIMARY KEY (user_id),
    CONSTRAINT fk8mn3uq07p24p78r5jkcc43ot0 FOREIGN KEY (librarian_user_id)
        REFERENCES public.librarian (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fke6yo8tn29so0kdd1mw4qk8tgh FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)


CREATE TABLE IF NOT EXISTS person
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    dob integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    middle_name character varying(255),
    CONSTRAINT person_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS publisher
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    publisher_name character varying(255),
    CONSTRAINT publisher_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS report
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255),
    report_type character varying(255),
    published_by_id bigint NOT NULL,
    report_document_id bigint,
    CONSTRAINT report_pkey PRIMARY KEY (id),
    CONSTRAINT report_report_document_id_document_fkey FOREIGN KEY (report_document_id)
    REFERENCES document (id),
    CONSTRAINT report_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id)
);



CREATE TABLE IF NOT EXISTS search
(
    member_id bigint NOT NULL,
    document_id bigint NOT NULL,
    CONSTRAINT search_pkey PRIMARY KEY (document_id, member_id),
    CONSTRAINT search_member_id_member_fkey FOREIGN KEY (member_id)
    REFERENCES member (id),
    CONSTRAINT search_document_id_document_fkey FOREIGN KEY (document_id)
    REFERENCES document (id)
);



CREATE TABLE IF NOT EXISTS thesis
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    topic character varying(255),
    published_by_id bigint NOT NULL,
    thesis_document_id bigint,
    CONSTRAINT thesis_pkey PRIMARY KEY (id),
    CONSTRAINT thesis_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id),
    CONSTRAINT thesis_thesis_document_id_document_fkey FOREIGN KEY (thesis_document_id)
    REFERENCES document (id)
);



CREATE TABLE IF NOT EXISTS users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address1 character varying(255),
    address2 character varying(255),
    age integer NOT NULL,
    city character varying(255),
    dob integer NOT NULL,
    email_id character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    middle_name character varying(255),
    password character varying(255),
    phone_number character varying(255),
    state character varying(255),
    zip_code character varying(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- Cascading rules
alter table author drop constraint fk6hvf724whhl6gil5s4l1jefje;
alter table author add CONSTRAINT fk6hvf724whhl6gil5s4l1jefje FOREIGN KEY (document_id)
        REFERENCES public.document (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;

alter table author drop constraint fkd8cm5fy8qunfotg4xpdi1wad7;
alter table author add CONSTRAINT fkd8cm5fy8qunfotg4xpdi1wad7 FOREIGN KEY (person_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;

ALTER TABLE borrow_return drop CONSTRAINT fksx2o4lmqigt4ye8bxljc9cqn5;
ALTER TABLE borrow_return add CONSTRAINT fksx2o4lmqigt4ye8bxljc9cqn5 FOREIGN KEY (copy_id)
        REFERENCES public.copy (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;

alter table copy drop constraint fkr2cre03jsof7hlliv7f3id8qj;
alter table copy add CONSTRAINT fkr2cre03jsof7hlliv7f3id8qj FOREIGN KEY (document_id)
        REFERENCES public.document (id) MATCH SIMPLE
        ON UPDATE CASCADE
	 ON DELETE CASCADE;

alter table member drop constraint fke6yo8tn29so0kdd1mw4qk8tgh;
alter table member add constraint fke6yo8tn29so0kdd1mw4qk8tgh foreign KEY (user_id)
         REFERENCES public.users (id) MATCH SIMPLE
         ON UPDATE CASCADE
         ON DELETE CASCADE;

alter table book drop constraint fk62e1mk4is3ldor7vqv6q9e2h6;

alter table book add CONSTRAINT fk62e1mk4is3ldor7vqv6q9e2h6 FOREIGN KEY (document_id)
        REFERENCES public.document (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;

alter table librarian drop constraint fkyf2jsjbxmnic68p6un7arncq;
alter table librarian add CONSTRAINT fkyf2jsjbxmnic68p6un7arncq FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;