-- Library Management Migration Script


CREATE TABLE IF NOT EXISTS author
(
    document_id bigint NOT NULL,
    person_id bigint NOT NULL,
    CONSTRAINT author_pkey PRIMARY KEY (document_id, person_id),
    CONSTRAINT author_document_id_fkey FOREIGN KEY (document_id)
        REFERENCES document (id),
    CONSTRAINT author_person_id_fkey FOREIGN KEY (person_id)
        REFERENCES person (id)
);


CREATE TABLE IF NOT EXISTS book
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    category character varying(255),
    edition integer NOT NULL,
    isbn character varying(255),
    title character varying(255),
    year integer NOT NULL,
    book_document_id bigint,
    published_by_id bigint NOT NULL,
    CONSTRAINT book_pkey PRIMARY KEY (id),
    CONSTRAINT book_publisher_published_by_id_fkey FOREIGN KEY (published_by_id)
        REFERENCES publisher (id),
    CONSTRAINT book_document_book_document_id_fkey FOREIGN KEY (book_document_id)
        REFERENCES document (id)
);


CREATE TABLE IF NOT EXISTS borrow_return
(
    borrow_date timestamp without time zone NOT NULL,
    due_date timestamp without time zone,
    is_overdue boolean NOT NULL,
    return_date timestamp without time zone,
    copy_id bigint NOT NULL,
    borrowed_by_id bigint NOT NULL,
    CONSTRAINT borrow_return_pkey PRIMARY KEY (borrow_date, borrowed_by_id, copy_id),
    CONSTRAINT borrowreturn_member_borrowed_by_id_fkey FOREIGN KEY (borrowed_by_id)
        REFERENCES member (id),
    CONSTRAINT borrowreturn_copy_copy_id_fkey FOREIGN KEY (copy_id)
        REFERENCES copy (id)
);


CREATE TABLE IF NOT EXISTS cite
(
    cited_document_id bigint NOT NULL,
    cited_by_document_id bigint NOT NULL,
    CONSTRAINT cite_pkey PRIMARY KEY (cited_by_document_id, cited_document_id),
    CONSTRAINT cite_document_cited_by_document_id_fkey FOREIGN KEY (cited_by_document_id)
        REFERENCES document (id),
    CONSTRAINT cite_document_cited_document_id_fkey FOREIGN KEY (cited_document_id)
        REFERENCES document (id)
);


CREATE TABLE IF NOT EXISTS contributor
(
    person_id bigint NOT NULL,
    issue_id bigint NOT NULL,
    CONSTRAINT contributor_pkey PRIMARY KEY (issue_id, person_id),
    CONSTRAINT contributor_issue_issue_id_fkey FOREIGN KEY (issue_id)
        REFERENCES issue (id),
    CONSTRAINT contributor_person_person_id_fkey FOREIGN KEY (person_id)
        REFERENCES person (id)
);


CREATE TABLE IF NOT EXISTS copy
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    level integer NOT NULL,
    room_number integer NOT NULL,
    copy_of_document_id bigint NOT NULL,
    CONSTRAINT copy_pkey PRIMARY KEY (id),
    CONSTRAINT copy_copy_of_document_id_document_fkey FOREIGN KEY (copy_of_document_id)
        REFERENCES document (id)
);


CREATE TABLE IF NOT EXISTS document
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_date timestamp without time zone,
    deleted_date timestamp without time zone,
    hierarchical_classification character varying(255),
    updated_date timestamp without time zone,
    created_by_id bigint NOT NULL,
    deleted_by_id bigint,
    updated_by_id bigint,
    CONSTRAINT document_pkey PRIMARY KEY (id),
    CONSTRAINT document_created_by_id_librarian_fkey FOREIGN KEY (created_by_id)
        REFERENCES librarian (id),
    CONSTRAINT document_deleted_by_id_librarian_fkey FOREIGN KEY (deleted_by_id)
        REFERENCES librarian (id),
    CONSTRAINT document_updated_by_id_librarian_fkey FOREIGN KEY (updated_by_id)
        REFERENCES librarian (id)
);


CREATE TABLE IF NOT EXISTS editor
(
    person_id bigint NOT NULL,
    issue_id bigint NOT NULL,
    CONSTRAINT editor_pkey PRIMARY KEY (issue_id, person_id),
    CONSTRAINT editor_person_id_person_fkey FOREIGN KEY (person_id)
    REFERENCES person (id),
    CONSTRAINT editor_issue_id_issue_fkey FOREIGN KEY (issue_id)
    REFERENCES issue (id)
);


CREATE TABLE IF NOT EXISTS issue
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    published_at timestamp without time zone,
    title character varying(255),
    published_by_id bigint,
    CONSTRAINT issue_pkey PRIMARY KEY (id),
    CONSTRAINT issue_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id)
);


CREATE TABLE IF NOT EXISTS issued_in
(
    magazine_id bigint NOT NULL,
    issue_id bigint NOT NULL,
    CONSTRAINT issued_in_pkey PRIMARY KEY (issue_id, magazine_id),
    CONSTRAINT issued_in_issue_id_issue_fkey FOREIGN KEY (issue_id)
    REFERENCES issue (id),
    CONSTRAINT issued_in_magazine_id_magazine_fkey FOREIGN KEY (magazine_id)
    REFERENCES magazine (id)
);


CREATE TABLE IF NOT EXISTS journal
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    edition integer NOT NULL,
    title character varying(255),
    published_by_id bigint NOT NULL,
    CONSTRAINT journal_pkey PRIMARY KEY (id),
    CONSTRAINT journal_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id)
);


CREATE TABLE IF NOT EXISTS journal_article
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(255),
    journal_id bigint NOT NULL,
    journal_article_document_id bigint,
    CONSTRAINT journal_article_pkey PRIMARY KEY (id),
    CONSTRAINT journal_article_journal_article_document_id_document_fkey FOREIGN KEY (journal_article_document_id)
    REFERENCES document (id),
    CONSTRAINT journal_article_journal_id_journal_fkey FOREIGN KEY (journal_id)
    REFERENCES journal (id)
);


CREATE TABLE IF NOT EXISTS keyword
(
    keyword character varying(255),
    document_id bigint NOT NULL,
    CONSTRAINT keyword_pkey PRIMARY KEY (document_id),
    CONSTRAINT keyword_document_id_document_fkey FOREIGN KEY (document_id)
    REFERENCES document (id)
);


CREATE TABLE IF NOT EXISTS librarian
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    librarian_info_id bigint,
    CONSTRAINT librarian_pkey PRIMARY KEY (id),
    CONSTRAINT librarian_librarian_info_id_users_fkey FOREIGN KEY (librarian_info_id)
    REFERENCES users (id)
);



CREATE TABLE IF NOT EXISTS magazine
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    edition integer NOT NULL,
    name character varying(255),
    magazine_document_id bigint,
    published_by_id bigint NOT NULL,
    CONSTRAINT magazine_pkey PRIMARY KEY (id),
    CONSTRAINT magazine_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id),
    CONSTRAINT magazine_magazine_document_id_document_fkey FOREIGN KEY (magazine_document_id)
    REFERENCES document (id)
);


CREATE TABLE IF NOT EXISTS member
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    membership_coverage timestamp without time zone,
    managed_by_id bigint NOT NULL,
    member_info_id bigint,
    CONSTRAINT member_pkey PRIMARY KEY (id),
    CONSTRAINT member_managed_by_id_librarian_fkey FOREIGN KEY (managed_by_id)
    REFERENCES librarian (id),
    CONSTRAINT member_member_info_id_users_fkey FOREIGN KEY (member_info_id)
    REFERENCES users (id)
);


CREATE TABLE IF NOT EXISTS person
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    dob integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    middle_name character varying(255),
    CONSTRAINT person_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS publisher
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    publisher_name character varying(255),
    CONSTRAINT publisher_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS report
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255),
    report_type character varying(255),
    published_by_id bigint NOT NULL,
    report_document_id bigint,
    CONSTRAINT report_pkey PRIMARY KEY (id),
    CONSTRAINT report_report_document_id_document_fkey FOREIGN KEY (report_document_id)
    REFERENCES document (id),
    CONSTRAINT report_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id)
);



CREATE TABLE IF NOT EXISTS search
(
    member_id bigint NOT NULL,
    document_id bigint NOT NULL,
    CONSTRAINT search_pkey PRIMARY KEY (document_id, member_id),
    CONSTRAINT search_member_id_member_fkey FOREIGN KEY (member_id)
    REFERENCES member (id),
    CONSTRAINT search_document_id_document_fkey FOREIGN KEY (document_id)
    REFERENCES document (id)
);



CREATE TABLE IF NOT EXISTS thesis
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    topic character varying(255),
    published_by_id bigint NOT NULL,
    thesis_document_id bigint,
    CONSTRAINT thesis_pkey PRIMARY KEY (id),
    CONSTRAINT thesis_published_by_id_publisher_fkey FOREIGN KEY (published_by_id)
    REFERENCES publisher (id),
    CONSTRAINT thesis_thesis_document_id_document_fkey FOREIGN KEY (thesis_document_id)
    REFERENCES document (id)
);



CREATE TABLE IF NOT EXISTS users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address1 character varying(255),
    address2 character varying(255),
    age integer NOT NULL,
    city character varying(255),
    dob integer NOT NULL,
    email_id character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    middle_name character varying(255),
    password character varying(255),
    phone_number character varying(255),
    state character varying(255),
    zip_code character varying(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
