micronaut:
  application:
    name: librarymanagement
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/librarymanagement
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages: 'com.models'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

