micronaut:
  application:
    name: librarymanagement
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
            - http://localhost:3001
            - http://localhost:3002
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/librarymanagement
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages: 'com.models'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

